Bank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('useraccess.urls')),
    path('account/', include('account.urls')),

]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useraccess/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView



app_name = 'useraccess'






urlpatterns = [
    path("sign-up/",RegisterView, name='sign-up'),
    path("sign-in/",LoginView, name='sign-in'),
    path("sign-out/",LogoutView, name='sign-out'),

]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Paylio - Money Transfer and Online Payments HTML Template</title>
    
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>

    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

    <header class="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex header-area">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html">
                            <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo">
                        </a>
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbar-content">
                            <i class="fas fa-bars"></i>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Personal</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Freelancer Payments</a></li>
                                        <li><a class="nav-link" href="subscriptions.html">Subscriptions</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Business</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Business Payments</a></li>
                                        <li><a class="nav-link" href="business-account.html">Business Account</a></li>
                                        <li><a class="nav-link" href="corporate-card.html">Corporate Card</a></li>
                                        <li><a class="nav-link" href="expense-management.html">Expense Management</a></li>
                                        <li><a class="nav-link" href="budgeting-and-analytics.html">Budgeting</a></li>
                                        <li><a class="nav-link" href="integrations.html">Integrations</a></li>
                                        <li><a class="nav-link" href="invoice-management.html">Invoice</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="rewards.html">Rewards</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Company</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="about-us.html">About Us</a></li>
                                        <li><a class="nav-link" href="career.html">Career</a></li>
                                        <li><a class="nav-link" href="career-details.html">Career Details</a></li>
                                        <li class="dropend sub-navbar">
                                            <a href="javascript:void(0)" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                              data-bs-auto-close="outside">Blog</a>
                                            <ul class="dropdown-menu sub-menu shadow">
                                                <li><a class="nav-link" href="blog.html">Blog</a></li>
                                                <li><a class="nav-link" href="blog-details.html">Blog Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a class="nav-link" href="error.html">Error</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Help</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="help-center.html">Help Center</a></li>
                                        <li><a class="nav-link" href="help-center-category.html">Help Category</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="right-area header-action d-flex align-items-center max-un">
                                {% if request.user.is_authenticated %}
                                <a href="/admin" class="login cmdn-btn">Admin</a>
                                <a href="{% url 'useraccess:sign-out' %}" class="login cmn-btn">Sign Out</a>
                                {% else %}
                                <a href="{% url 'useraccess:sign-in' %}" class="login">Login</a>
                                <a href="{% url 'useraccess:sign-up' %}" class="cmn-btn">Sign Up
                                    <i class="fas fa-caret-right"></i>
                                </a>
                                {% endif %}
                                
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- alert start -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
                </script>
                <!-- alert end -->
            </div>
        </div>
        
    </header>
    <!-- header-section end -->

{% block content %}
  
{% endblock content %}


    
    <!--==================================================================-->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>