Bank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('useraccess.urls')),
    path('account/', include('account.urls')),

]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import index
from .transfare import search_using_account, AmountTranfare, AmountTranfareProcess,TransactionConfirmation,TransfarProcess, TransfarCompleted
from .transaction import transaction_list, transaction_detail
from .payment_request import SearchUserRequest, AmountRequest, AmountRequestProcess, RequestConfirmation, RequestCompleted, RequestFinialProcess, settlement_confirmation, settlement_processing, SettlementCompleted, delete_payment_request
from .credit_card import credit_card_detail, fund_credit_card, withdraw_credit_card, delete_card


app_name = 'core'



urlpatterns = [
    path("", index, name='index'),
    path('search-account/', search_using_account, name='search-account'),
    path('amount-transfare/<account_number>/',AmountTranfare , name='amount-transfare'),
    path('amount-transfare-process/<account_number>/',AmountTranfareProcess , name='amount-transfare-Process'),
    path('transfare-confirm/<account_number>/<transaction_id>/',TransactionConfirmation , name='transfare-confirmation'),
    path('transfare-process/<account_number>/<transaction_id>/',TransfarProcess , name='transaction-process'),
    path('transfare-completed/<account_number>/<transaction_id>/',TransfarCompleted , name='transfar-completed'),



    #transaction



    path('transaction/',transaction_list, name='transaction-list' ),
    path('transaction/<transaction_id>',transaction_detail, name='transaction-detail' ),

    #payment_request

    path('request-search-user/',SearchUserRequest, name='request-search-user' ),
    path('amount-request/<account_number>',AmountRequest, name='amount-request' ),
    path('amount-request-process/<account_number>/',AmountRequestProcess , name='amount-request-Process'),
    path('request-confirm/<account_number>/<transaction_id>/',RequestConfirmation , name='request-confirmation'),
    path('request-process/<account_number>/<transaction_id>/',RequestFinialProcess , name='request-finial-process'),
    path('request-completed/<account_number>/<transaction_id>/',RequestCompleted , name='request-completed'),
    path('settlement-confirmation/<account_number>/<transaction_id>/', settlement_confirmation, name='settlement-confirmation'),
    path('settlement-processing/<account_number>/<transaction_id>/',settlement_processing, name= 'settlement_processing'),
    path('settlement-completed/<account_number>/<transaction_id>/',SettlementCompleted , name='settlement-completed'),
    path('delete-request/<account_number>/<transaction_id>/',delete_payment_request , name='delete-request'),

    # credit_card

    path('card/<card_id>/', credit_card_detail, name="card_detail" ),
    path('fund-credit-card/<card_id>/',fund_credit_card, name= "fund-credit-card" ),
    path('withdraw-credit-card/<card_id>/',withdraw_credit_card, name= "withdraw-credit-card" ),
    path('delete-credit-card/<card_id>/',delete_card, name= "delete-card" ),




]

templates/transfare/amount-transfare.html
{% extends 'partials/dashboard-base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img style="width: 100px; hight: 100px; border-radius: 50%" src="{{account.user.kyc.image.url}}" alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{account.user.kyc.full_name|title}}</p>
                                        <p>{{account.account_number|title}}</p>
                                        <small>{{account.user.email}}</small>
                                    </div>
                                </div>
                                <div class="right">
    
                                    <a href="{% url 'core:search-account' %}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'core:amount-transfare-Process' account.account_number %}" method = "POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="{{ request.user.account.account_balance|intcomma}}" name="amount-send" type="number" id="amount-send">
                                <select>
                                    <option value="1">USD</option>
                                    <option value="2">USD</option>
                                    <option value="3">USD</option>
                                </select>
                            </div>
                            <p>Available Balance<b>${{request.user.account.account_balance}}</b></p>
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <div class="send-banance">
                            <span class="mdr">Payment Decsription</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="payment for fees" name="description" type="text" >
                                <select>
                                    <option value="1">USD</option>
                                    <option value="2">USD</option>
                                    <option value="3">USD</option>
                                </select>
                            </div>
                          
                        </div>




                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{ request.user.account.account_balance }}" 
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount-send")
                                let sendAmount = sendAmount_input.value
                                let errorDiv = document.getElementById("error-div")
                                let total_to_pay = document.getElementById('total-to-pay')

                                let errors = []
                                new_bal = available_balance - sendAmount
                                new_balance.innerHTML = `New Balance <b> $${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                                total_to_pay.innerHTML = `USD <b> $${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                                if (new_bal < 0){
                                    new_balance.style.color = "red"
                                    alert('You can only send $' + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))

                                }else{
                                    new_balance.style.color = 'black'
                                }

                            }
                        </script>
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li>
                                <h5>Total To Pay</h5>
                            </li>
                            <li>
                                <h5 id="total-to-pay">USD 0.00</h5>
                            </li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/transfare/transaction-confirmation.html
{% extends 'partials/dashboard-base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img style="width: 100px; hight: 100px; border-radius: 50%" src="{{account.user.kyc.image.url}}" alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{account.user.kyc.full_name|title}}</p>
                                        <p>{{account.account_number|title}}</p>
                                        <small>{{account.user.email}}</small>
                                    </div>
                                </div>
                              
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver</span>
                                        <b><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="d3bebca1a1baa0e1e193b4beb2babffdb0bcbe">{{transaction.reciver.email}}</a></b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Pay</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>We have sent a verification code on your phone + Number +44831***932. Please enter verification code below</p>
                                            <form action="{% url 'core:transaction-process' account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input type="text" minlength="4" maxlength="4" name="pin-number">
                                                    
                                                </div>
                                                <a href="javascript:void(0)">Don’t receive a code?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="assets/images/icon/success.png" alt="icon">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}

templates/transfare/transfar-completed.html
{% extends 'partials/dashboard-base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Submitted</h3>
                            <p>Payment request <b>{{transaction.transaction_id}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b> View Detail</b></a> | <a href=""><b> Send Another Payment</b></a></h5>
                        </div>
                        <!--
                        <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div>
                        -->
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}